import fs from 'fs';
import path from 'path';
import { binShimFile, hookSourceFile } from './paths-cursor.mjs';
import { HookScope, hooksStatus, installHooks } from './hooks-install.mjs';
import { PLUGIN_ROOT, pluginHooksAlive, readHookSource } from './hook-source.mjs';

// Self-install: what a marketplace install cannot do for itself.
//
// Cursor installs a plugin by cloning the marketplace repo into
// `plugins/cache/<marketplace>/<plugin>/<git-sha>/` — a directory whose name changes on every
// upgrade. Two things follow, and both are handled here:
//
//   1. The bundled `hooks/hooks.json` reaches only some of the hosts, and nothing readable says
//      whether it reached this one: Cursor discards a plugin's hooks entirely when third-party
//      extensibility is off, and says so only in an output channel — and `cursor-agent` never runs
//      them at all, whatever the setting (Cursor staff, forum 163890). So the user-scope registry is
//      installed and then LEFT installed, permanently, because it is the only registry the CLI
//      reads. The two overlap on a machine that runs both, and the duplicate sidecar lines that
//      produces are collapsed by the reader on the host's own event id — see lib/delta-cursor.mjs.
//   2. `~/.beezi-cursor/bin/beezi.mjs`, a shim forwarding to whichever copy is installed, so a
//      human has one stable path to type. Nothing the plugin ships depends on it — the skills name
//      `${CURSOR_PLUGIN_ROOT}/scripts/…` directly, which Cursor expands for them, and which works
//      on the first session rather than the second.
//
// This runs from the MCP server's startup, which Cursor spawns once per session from the installed
// copy — the one process that always knows where the plugin actually lives. It is best-effort
// throughout: a machine that cannot be repaired must still get its MCP tools.

const SHIM_COMMANDS = Object.freeze({
  login: 'login.mjs',
  logout: 'logout.mjs',
  me: 'me.mjs',
  track: 'track.mjs',
  install: 'install.mjs',
  plan: 'billing-capture.mjs',
  // Same script as `plan`; `refresh` is the verb the beezi-refresh skill and the session-start
  // nudge both name, and a shim that does not know it prints "unknown command".
  refresh: 'billing-capture.mjs',
  // The independent surface for diagnostics consent. A skill alone would not do: the moment a user
  // most wants to turn crash reporting off is the moment the agent is not working.
  telemetry: 'telemetry.mjs',
  // Symmetry, not a defect fix: skills/beezi-sync/SKILL.md invokes scripts/sync.mjs directly, so
  // nothing was broken — but every other user-facing verb has a shim, and `beezi sync` printing
  // "unknown command" is a worse answer than running the thing.
  sync: 'sync.mjs',
});

// argv is rewritten before the import so the target script sees exactly the arguments it would have
// seen had node started it directly — every script reads `process.argv.slice(2)`.
//
// The GENERATED text is held to the same Node 13.2 floor as the rest of the plugin, and for a
// sharper reason: this file is written to the user's home and run by whatever `node` they have, so
// it is the one piece of the plugin whose interpreter nobody chose. Bare builtin specifiers (the
// `node:` prefix does not resolve below 12.20/14.13.1), no `?.`/`??`, and the dynamic import inside
// an async IIFE because top-level await needs 14.8.
export function shimBody(pluginRoot, commands = SHIM_COMMANDS) {
  return `// GENERATED by the Beezi Cursor plugin — do not edit.
// Regenerated on every Cursor session; points at the installed plugin copy.
import path from 'path';
import url from 'url';

const ROOT = ${JSON.stringify(pluginRoot)};
const COMMANDS = ${JSON.stringify(commands, null, 2)};

const [sub, ...rest] = process.argv.slice(2);
const script = COMMANDS[sub];
if (!script) {
  console.error(\`Beezi: unknown command '\${sub == null ? '' : sub}'. Use one of: \${Object.keys(COMMANDS).join(', ')}.\`);
  process.exit(1);
}
const target = path.join(ROOT, 'scripts', script);
process.argv = [process.argv[0], target, ...rest];
// The .catch is what top-level await used to give for free: a failed import exits non-zero. Without
// it, an async IIFE's rejection is merely an unhandled rejection — a warning and exit code 0 below
// Node 15 — so a command that never ran would report success.
(async () => {
  await import(url.pathToFileURL(target).href);
})().catch((error) => {
  console.error(error);
  process.exit(1);
});
`;
}

// Rewritten only when the content differs: this runs at every session start, and an unchanged
// rewrite would churn the file for nothing.
export function writeBinShim({ pluginRoot = PLUGIN_ROOT, file = binShimFile() } = {}) {
  const body = shimBody(pluginRoot);
  let current = null;
  try { current = fs.readFileSync(file, 'utf-8'); } catch { /* absent */ }
  if (current === body) return { file, written: false };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body, 'utf-8');
  return { file, written: true };
}

export function ensureInstalled({
  pluginRoot = PLUGIN_ROOT,
  now = Date.now(),
  shimFile = binShimFile(),
  sourceFile = hookSourceFile(),
  statusDeps = {},
  installDeps = {},
} = {}) {
  const actions = [];
  try {
    const { written } = writeBinShim({ pluginRoot, file: shimFile });
    if (written) actions.push('shim');
  } catch (error) {
    actions.push(`shim-failed:${error == null || error.code == null ? 'error' : error.code}`);
  }

  try {
    // The user-scope registry goes in and stays in, whatever the bundled one is doing.
    //
    // This used to remove it the moment a bundled hook was seen to fire, on the reasoning that two
    // registries mean two copies of every hook. They do — but they are not two copies of the same
    // COVERAGE: `cursor-agent` does not run a plugin's bundled hooks at all, so the entries deleted
    // here were the CLI's only ones. One IDE session was enough to trigger the removal, and every
    // CLI session on that machine afterwards reported nothing, silently, with the plugin's own
    // status output insisting the hooks were fine. The duplicate lines the overlap produces are
    // collapsed at read time now, on the id the host stamps on the event itself.
    const status = hooksStatus({ scope: HookScope.USER, scriptsDir: path.join(pluginRoot, 'scripts'), ...statusDeps });
    if (status.state !== 'installed') {
      installHooks({ scope: HookScope.USER, materialize: false, sourceRoot: pluginRoot, ...installDeps });
      actions.push(`user-hooks-installed:${status.state}`);
    }
    // Which registry has actually been seen firing here. Reported, never acted on: `scripts/mcp.mjs`
    // prints it and the status skill quotes it, and "no bundled hook has ever run on this machine"
    // is the one signal that tells a CLI-only install apart from a broken one.
    const source = pluginHooksAlive({ probe: readHookSource({ file: sourceFile }), now, pluginRoot })
      ? 'plugin-hooks'
      : 'launcher';
    return { source, actions };
  } catch (error) {
    actions.push(`hooks-failed:${error == null || error.message == null ? 'error' : error.message}`);
    return { source: 'unknown', actions };
  }
}
